# Site settings
title: Christian L. Ebbesen, PhD
tagline: "list of publications"
url: "https://chrelli.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/2017_motor_splash_kopi.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
